copyright: Copyright &copy; 2021 Wolfgang Richter

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wolfgang-richter-b4730934/
    - icon: fontawesome/brands/github
      link: https://github.com/theonewolf
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/theonewolf
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/theonewolf87
    - icon: fontawesome/brands/flickr
      link: https://www.flickr.com/photos/29905928@N05/
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/theonewolf

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - toc:
      permalink: true
  - smarty

plugins:
  - search:
      prebuild_index: true

theme:
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  favicon: assets/wolf-favicon.png
  font:
    text: MathJax TeX
    code: Source Code Pro
  logo: assets/wolf-logo.png
  name: material
  palette:
    primary: black
    accent: light blue
    scheme: preference

site_name: Wolfgang Richter
