site_name: Wolfgang Richter

theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  name: material

markdown_extensions:
  - meta
  - toc:
      permalink: true
